language: c

before_install:
  - sudo bash bootstrap.sh
  - git clone git@github.com:xtuple/xtuple.git --recursive
  - cd xtuple
  - n stable
  - npm install
  - cd ..

install:
  - n 0.11.13
  - npm install
  - npm install -g

script:
  - sudo npm test xtuple-server-lib
  - sudo npm test

after_failure:
  - pg_lsclusters 
  - cat npm-debug.log
  - cat nex-debug.log
  - cat xtuple-server-test.log

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: "Dg+WqvgoTUf4Cm7JnbcThsjuvnuKPvxqy2SPZMDmgP1goYW64LvSXOa+LcVz2Pof/CX78922oUa3S+FWJ1erzIsFaMbiBP9arEK1tM1V89IMkwwv6rMhMHLGDHQSelal6N3SI5yplPWXtQux6vVEyDWUzGQ4+KWtdnHd/c2vIVE="
  on:
    tags: true
    repo: xtuple/xtuple-server
    all_branches: true
